name: Example workflow for Codecov
on: [push]
jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - name: Upload coverage to Codecov
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
