name: Documentation Publisher

#on:
#  schedule:
#  - cron: "0 0 * * *"

on: [push, pull_request]

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}

        args: "--min-acl=private --swift-build-tool xcodebuild "
