name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -scheme COSC345-ProjectTests -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro' -enableCodeCoverage YES;
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
    - name: Upload coverage to Codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r report.xml;
  

