name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild build test -scheme COSC345-Project -project COSC345-Project.xcodeproj -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro'
