name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
#     - name: Force Xcode 11
#       run: sudo xcode-select -switch /Applications/Xcode_12.3.app
    - name: Run tests
      run: xcodebuild test -scheme COSC345-ProjectTests -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro' -enableCodeCoverage YES;
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
          name: code-coverage-report
          path: /Users/runner/Library/Developer/Xcode/DerivedData/COSC345-Project-fbgeqhdeqvqzbsfydxlorjctniwm/Logs/Test/Test-COSC345-ProjectTests-2021.07.29_00-01-33-+0000.xcresult
          
#     - name: install swiftLint
#       run: brew install swiftlint
#       run: swiftlint
#     - name: Upload coverage to Codacy
#       run: bash <(curl -Ls https://coverage.codacy.com/get.sh);
  

