#!/bin/bash
if compgen -ac | grep -i 'jazzy'; then
    echo "jazzy is already installed"
    ls
    jazzy --min-acl=private --swift-build-tool xcodebuild
    rm -rf ./build
else
    echo "jazzy is not installed, trying to install"
    osascript -e 'tell application "Terminal" to set miniaturized of every window to false'
    sudo gem install jazzy
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "jazzy is now installed"
    osascript -e 'tell application "Terminal" to quit'
fi
